### PR TITLE
SFB-72: Create custom codelists

### PR DESCRIPTION
**Pull request by JonasVanHoof**
## ID
 [SFB-72](https://binnenland.atlassian.net/browse/SFB-72)

 ## Description

 Sometimes the available codelists are not enough for that we want to be able to create our own. This PR is a start in that direction.

 ## Type of change

 - [ ] Bug fix
 - [x] New feature
 - [ ] Breaking change
 - [ ] Other

 ## How to test

**This is not finished yet**
Create your own list.

 ## Links to other PR's

 - /

### CODE REVIEW

**Comment by JonasVanHoof** [comment]
**Created form with generation of form => this is not fully functional**

generate_codelist_f25_11_2023

**Creation with html and css**

create_codelist_view_html_25_11_2023

**Comment by aatauil** [comment]
Looks nice! Maybe we should sit together to make some mockups together. Defenitly step in right direction though, feel free to ping me ;) 

Also could you convert this PR to draft? just so everyone knows its not ready for review/merge yet

**Comment by JonasVanHoof** [comment]
**Note:**

Rebased with master. As the master branch now uses the common Preview form this PR are needs an update.. 
image

**Comment by JonasVanHoof** [comment]
Closing this PR as we will be implementing this just a little differently than in here. We are going to mirror the GN codelist creation page like in here https://reglementairebijlagen.lblod.info/codelists-management

**Pull request closed without merging**
