### PR TITLE
Add listing item reordering

### PR DESCRIPTION
**Pull request by Windvis**
This uses the new reordering feature to the builder form listings.

I didn't add it to the "validations" listing since the order there doesn't really matter _I think_?

### CODE REVIEW

**Comment by JonasVanHoof** [comment]
> This uses the new reordering feature for the builder form listings.
> 
> I didn't add it to the "validations" listing since the order there doesn't really matter _I think_?

Atm this will not be needed thanks for checking!

**Review by JonasVanHoof — APPROVED** [review]

**Comment by Windvis** [comment]
Hmmmm, I noticed something strange with the order field now. After changing the order with the new buttons, the preview is updated and it shows the correct order, but the value in the order field isn't updated.

The input field doesn't have an observer so it doesn't update the visible value even if the graph was updated. Should we just remove the order input field and depend on the order in the builder form?

**Comment by Windvis** [comment]
Aaaand I noticed a regression in the addon 😬 whoops.

**Comment by Windvis** [comment]
> Edit: I removed the order field for now. It has the disadvantage that you can't order things by hand but I don't think we want users to do that anyways. This could become an issue because of the listings though. They are fields in the same property group, but their ordering count is separate from the other fields because they are created in a different listing 🤔.

It seems it wasn't possible to modify the order of the listings compared to the normal fields in the previous version either, so this didn't break that.

**Pull request merged**
