### PR TITLE
SFB-72: extend basic functionality with create and edit

### PR DESCRIPTION
**Pull request by JonasVanHoof**
## ID
 [SFB-72](https://binnenland.atlassian.net/browse/SFB-72)

 ## Description

The user wants to have a new interface where they want to see and edit code lists. The generic code lists may not be edited but the others can. I created a new page for showing the code lists and viewing them. And added a tag that will tell you if it is a public or private codelist.

When clicking the create button it create a new codelist with the default name . You have to change that name to proceed. On the edit page some buttons are enabled or disabled depending if the codelist is public or not.

 ## Type of change

 - [ ] Bug fix
 - [x] New feature
 - [ ] Breaking change
 - [ ] Other

 ## How to test

1. See the overview page are the tags correct
2. Click on a codelist and see if you can edit/delte it
3. Create your own codelist and see if you can edit/delete it

 ## Links to other PR's

 - https://github.com/lblod/frontend-form-builder/pull/84

### CODE REVIEW

**Comment by JonasVanHoof** [comment]
Edit controller for codelijsten should be refactored and more split up into general methods

**Review by ZijneDwaasheid — COMMENTED** [review]
The toaster messages are little bit all over the place here, especially when you try weird things :) So, you can actually save a new code list with empty concepts. It will delete them,  but then you get a lot of toaster messages: 1 saying "succesvol verwijderd + id", not the message that you expect when you save something and a lot of messages that say kan concept niet werwijderen + id.

Then when editing, I think you tried to disable the save button. So when adding empty concepts you can't save. You can if just remove one of the empty concepts.

**Comment by JonasVanHoof** [comment]
**Current state resolves**
- Checks for the save button to be:
  - conceptscheme: isPrivate => disabled
  - name: unchanged name => disabled
  - concept labels: unchanged => disabled
  - n concept labels are empty: unchanged => disabled
  - name + concepts: name changed but concept label is empty => disabled
  - concept + n concept label is empty: => disabled
  - name changed + concept removed + added new concept + empty concept label => disabled
  - when concept added and than removed in the same edit session: disabled
  - // is enabled when
  - name: changed => enabled
  - concept-list: changed => enabled
  - concept: removed => enabled

**commit:** https://github.com/lblod/frontend-form-builder/pull/85/commits/ca75d9bd1560ccc251abd47a64650cf8b08f9f56

**Comment by JonasVanHoof** [comment]
Added a property `isPublic` to the concept-scheme domain to know if the items are are public or private. Commit here https://github.com/lblod/app-form-builder/commit/3c472bb3cfd9c5b2a8b21d799d930757b6519b0c

**Review by ZijneDwaasheid — COMMENTED** [review]
Works as expected. Can create, edit and see the public code-lists marked by a label. previous issues are solved:)

**Pull request merged**
